path:
  ckpt_path: "../MG-Data/output/ckpt"
  log_path: "../MG-Data/output/log"
  result_path: "../MG-Data/output/result"
  time: "2023-03-12-20_53" # "2023-03-13-03_54"
random_seed: 37
num_gpus: 4
optimizer:
  batch_size: 24
  group_size: 6
  learning_rate: 0.0001
  grad_clip_thresh: 1.0
step:
  total_step: 100000
  log_step: 100
  save_step: 100
  val_step: 1000
  synth_step: 1000
  total_epoch: 1000
  log_epoch: 1
  save_epoch: 1
  val_epoch: 1
  synth_epoch: 10
test:
  test_size: 4
dist_config:
  "dist_backend": "nccl"
  "dist_url": "tcp://localhost:54325"
  "world_size": 1
