dataset: "LJSpeech"

path:
  corpus_path: "../All_Data/Data/LJSpeech/wavs"
  preprocessed_path: "../MG-Data/preprocessed_data/LJSpeech"

preprocessing:
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  g2p:
    dict_path: 'resources/cmu_dictionary'
    add_blank: False
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000
  spk:
    n_spks: 1
    spk_emb_dim: 64
  dataform:
    name_col: 0
    speaker_col: 1000
    phone_col: 1000
    raw_text_col: 1